Sort apps by package name
nickbutcher/AdaptiveIconPlayground pull request #15
Opened 2018-08-17 00:59 UTC by TarasMazepa

So users will get at least some predictability when they see list of icons :)

2018-08-17 09:01 UTC, nickbutcher commented on app/src/main/java/uk/co/nickbutcher/adaptiveiconplayground/MainActivity.kt
> +            apps.sortBy { it.packageName }
Can you do this fluently i.e.

```
val apps = pm.getInstalledApplications(0)
    .sortBy { it.packageName }
    .forEach { appInfo -> 
    …
```

2018-08-17 09:02 UTC, nickbutcher requested changes
Thanks for the contribution, one small comment.

2018-08-17 09:06 UTC, TarasMazepa commented
sortBy returns Unit. To do this fluently apply should be used :)

2018-08-17 17:51 UTC, TarasMazepa commented on app/src/main/java/uk/co/nickbutcher/adaptiveiconplayground/MainActivity.kt
> +            apps.sortBy { it.packageName }
done

2018-08-17 17:53 UTC, TarasMazepa commented
I signed it!

2018-09-10 21:28 UTC, TarasMazepa commented
Hey, please merge!

2019-04-25 17:40 UTC, TarasMazepa commented
@nickbutcher can you please merge this change?

2024-08-19 17:22 UTC, closed without merging