Null checks on icons to stop crashes
nickbutcher/AdaptiveIconPlayground pull request #18
Opened 2018-11-22 14:30 UTC by toth3max

Added null checks for the icons so that badly formated apps with insufficient icon meta data won't make the app crash while loading the icons.

2018-11-23 10:00 UTC, nickbutcher requested changes

2018-11-23 10:00 UTC, nickbutcher commented on app/src/main/java/uk/co/nickbutcher/adaptiveiconplayground/AdaptiveIconView.kt
> +        if(icon.background != null) {
More idomatic kotlin might be:

`icon.background?.let { rasterize(it, background, c) }`

2018-11-26 13:08 UTC, toth3max commented
Very true! The latest commit uses this style for the null checks.

2018-11-26 15:20 UTC, nickbutcher approved these changes

2018-11-26 15:20 UTC, merged

2018-11-26 15:20 UTC, nickbutcher commented
Thanks for the contribution!